server:
  port: 9002
  
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root